# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


target 'codepath_wk1e1' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 1.1.5'

pod 'Snap', '~> 0.9.1'

end

target 'codepath_wk1e1Tests' do

end

